app/site/__init__.py
from flask import Blueprint

site = Blueprint('site', __name__, template_folder='templates')

from . import routes

app/site/routes.py
from flask import (render_template, redirect, url_for)
from flask_login import login_required, current_user
import urllib.request, urllib.parse, json
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

from . import site
from ..auth.models import Song
from ..auth.forms import SongForm

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/song-tracks/<artist_name>')
def songTracks(artist_name):
    client_id = 'e43992d0447145cbb3f50e580d7126cf'
    client_secret = 'da0aab427ff24a4aabce560937ad3a0b'
    sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(client_id=client_id, client_secret=client_secret))
    results = sp.search(q=artist_name, limit=20, type='artist')
    artist_id = results['artists']['items'][0]['id']
    tracks = sp.artist_top_tracks(artist_id=artist_id)
    return render_template('song_tracks.html', tracks=tracks['tracks'], artist_name=artist_name)

@site.route('/profile')
@login_required
def profile():
    songs = Song.get_by_user_id(current_user.id)
    return render_template('profile.html', songs=songs)

@site.route('/song/<id>/edit', methods=["GET", "POST"])
@login_required
def songEdit(id):
    song = Song.get_by_id(id)
    form = SongForm(obj=song)
    error = None
    if form.validate_on_submit():
        song.name = form.name.data
        song.guitar = form.guitar.data
        song.amp = form.amp.data
        song.pedals = form.pedals.data
        song.style = form.style.data
        song.groove = form.groove.data
        song.save()
        return redirect(url_for('site.profile'))
    return render_template('song_form.html', form=form, error=error)

@site.route('/song/add', methods=["GET", "POST"])
@login_required
def songAdd():
    song = Song()
    form = SongForm(obj=song)
    error = None
    if form.validate_on_submit():
        song.user = current_user
        song.name = form.name.data
        song.guitar = form.guitar.data
        song.amp = form.amp.data
        song.pedals = form.pedals.data
        song.style = form.style.data
        song.groove = form.groove.data
        song.save()
        return redirect(url_for('site.profile'))
    return render_template('song_form.html', form=form, error=error)

@site.route('/song/<id>/remove', methods=["GET", "POST"])
@login_required
def songRemove(id):
    song = Song.get_by_id(id)
    song.delete()
    return redirect(url_for('site.profile'))

app/site/templates/index.html
{% extends 'base_template.html' %}

{% block content %}
<div class="row content">
    <div class="col-sm-2 sidenav">
        <nav class="navbar navbar-light bg-light">
            <br>
            <br>
            <br>
            <nav class="navbar navbar-light bg-light">
                <a class="navbar-brand" href="#">
                    <img src="/static/images/silvsky.webp" width="100%" alt="">
                </a>
            </nav>
        </nav>
    </div>
    <div class="col-sm-8 text-left">
        <h1>Remember the tones you create</h1>
        <p></p>
        <hr>
        <h3>Here at Music is Cool</h3>
        <p>We love to play music. Rock, Jazz, RnB, Rap, Punk, Metal, ambient, Shoegaze. Whatever type of music you can
            think of, we are down to jam. However sometimes when you're jamming you get caught up in the groove and music
            and forget different jams, progressions, licks, solos, rhythyms. So why not try to write them down so you never forget them.
            Arranging music is hard and it is especially hard when you try to keep it all in your head.
            <br>
            <br>
        <p>So with this Website we are going to try to allow you to record that amazing riff that you can't remember what key
            you were in or that bVI chord that shouldn't work in your progrssion but sounds amazing.
        </p>
        <div id="flex-container">
            <div>
                <img align="right" src="/static/images/nirv.jpg" width="55%" top="-150px" alt="">
            </div>
            <div>
                <a href="{{ url_for('site.songTracks', artist_name='Gary Clark Jr') }}">
                    <img src="/static/images/clark.jpg" class="center" alt="">
                    <p>Gary Clark Jr.</p>
                </a>
            </div>
            <div>
                <a href="{{ url_for('site.songTracks', artist_name='Jerry Garcia') }}">
                    <img src="/static/images/garcia.jpg" class="center" alt="">
                    <p>Jerry Garcia</p>
                </a>
            </div>
            <div>
                <a href="{{ url_for('site.songTracks', artist_name='Prince') }}">
                    <img src="/static/images/prnc.jpg" class="center" alt="">
                    <p>Prince</p>
                </a>
            </div>
                
            <img align="right" src="/static/images/replac.jpg" width="50%" top="-10px" alt="">
        </div>
    </div>
</div>
{% endblock %}

app/site/templates/profile.html
{% extends 'base_template.html' %}

{% block content %} 
    <section class="bg-dark text-light text-center shadow mb-20">
        <div class="container p-5 bg-dark">
            <div class="row">
                <div class="d-md-flex bg-dark align-items-center justify-content-evenly">
                    <h1 class="col text-center">{{ current_user.name }}'s user profile</h1>
                </div>
            </div>
        </div>
    </section>

    <section class="text-center">
    <div class="container p-10">
        <div class="row"><br>
            <h3 class="p-5">Here are your Scratch Song Details</h3>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Guitar</th>
                    <th>Amp</th>
                    <th>Pedals</th>
                    <th>Style</th>
                    <th>Groove</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for song in songs %}
                <tr>
                    <td>{{ song.name }}</td>
                    <td>{{ song.guitar }}</td>
                    <td>{{ song.amp }}</td>
                    <td>{{ song.pedals }}</td>
                    <td>{{ song.style }}</td>
                    <td>{{ song.groove }}</td>
                    <td>
                        <a href="{{ url_for('site.songEdit', id=song.id) }}" class="btn btn-info">Edit</a>
                        <a href="{{ url_for('site.songRemove', id=song.id) }}" class="btn btn-danger">Remove</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <a href="{{ url_for('site.songAdd') }}" class="btn btn-primary">Add</a>
        </div>
        <div class="row" style="margin-top: 20px;">
            <div class="col-4"></div>
            <div class="col-3 p-10">
                <img src="../static/images/replac.jpg" class="d-flex align-items-center justify-content-center p-50 img-fluid" alt="">
            </div>
            <div class="col-3"></div>
        </div>
    </div>
    </section>
{% endblock %}

app/site/templates/song_form.html
{% extends 'index.html' %}

{% block title %}Edit your song{% endblock %}

{% block content %}
{% if error %}
<p style="color: red;"><strong>Error:</strong> {{ error }}
    {% endif %}
<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <div>
        {{ form.name.label }}
        {{ form.name(size=64) }}
        <br>
        {% for error in form.name.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </div>
    <div>
        {{ form.guitar.label }}
        {{ form.guitar(size=64) }}
        <br>
        {% for error in form.guitar.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </div>
    <div>
        {{ form.amp.label }}
        {{ form.amp(size=64) }}
        <br>
        {% for error in form.amp.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </div>
    <div>
        {{ form.pedals.label }}
        {{ form.pedals(size=64) }}
        <br>
        {% for error in form.pedals.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </div>
    <div>
        {{ form.style.label }}
        {{ form.style(size=64) }}
        <br>
        {% for error in form.style.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </div>
    <div>
        {{ form.groove.label }}
        {{ form.groove(size=64) }}
        <br>
        {% for error in form.groove.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </div>
    <div>
        {{ form.submit() }}
    </div>
</form>
{% endblock %}

app/site/templates/song_tracks.html
{% extends 'base_template.html' %}

{% block content %}
<div class="row content">
    <div class="col-sm-12 text-left">
        <h1>Showing tracks for "{{ artist_name }}" artist</h1>
        {% for track in tracks %}
        <div class="panel panel-default">
            <div class="panel-heading">{{ track.name }}</div>
            <div class="panel-body">
                <audio controls>
                    <source src="{{ track.preview_url }}">
                </audio>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}