app/__init__.py
import os

from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

login_manager = LoginManager()
db = SQLAlchemy()
migrate = Migrate()

def create_app():
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    app.config.from_pyfile('config.py', silent=True)
    app.config['SQLALCHEMY_DATABASE_URI'] = "postgresql://postgres:%40Pookas69@localhost:5432/music"
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SECRET_KEY'] = 'secret'

    login_manager.init_app(app)
    login_manager.login_view = "auth.login"

    db.init_app(app)
    migrate.init_app(app, db)

    from .site import site
    app.register_blueprint(site)

    from .auth import auth
    app.register_blueprint(auth)

    return app

app/site/__init__.py
from flask import Blueprint

site = Blueprint('site', __name__, template_folder='templates')

from . import routes

app/site/routes.py
from flask import (render_template, redirect, url_for)
from flask_login import login_required, current_user
import urllib.request, urllib.parse, json
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

from . import site
from ..auth.models import Song
from ..auth.forms import SongForm

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/song-tracks/<artist_name>')
def songTracks(artist_name):
    client_id = 'e43992d0447145cbb3f50e580d7126cf'
    client_secret = 'da0aab427ff24a4aabce560937ad3a0b'
    sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(client_id=client_id, client_secret=client_secret))
    results = sp.search(q=artist_name, limit=20, type='artist')
    artist_id = results['artists']['items'][0]['id']
    tracks = sp.artist_top_tracks(artist_id=artist_id)
    return render_template('song_tracks.html', tracks=tracks['tracks'], artist_name=artist_name)

@site.route('/profile')
@login_required
def profile():
    songs = Song.get_by_user_id(current_user.id)
    return render_template('profile.html', songs=songs)

@site.route('/song/<id>/edit', methods=["GET", "POST"])
@login_required
def songEdit(id):
    song = Song.get_by_id(id)
    form = SongForm(obj=song)
    error = None
    if form.validate_on_submit():
        song.name = form.name.data
        song.guitar = form.guitar.data
        song.amp = form.amp.data
        song.pedals = form.pedals.data
        song.style = form.style.data
        song.groove = form.groove.data
        song.save()
        return redirect(url_for('site.profile'))
    return render_template('song_form.html', form=form, error=error)

@site.route('/song/add', methods=["GET", "POST"])
@login_required
def songAdd():
    song = Song()
    form = SongForm(obj=song)
    error = None
    if form.validate_on_submit():
        song.user = current_user
        song.name = form.name.data
        song.guitar = form.guitar.data
        song.amp = form.amp.data
        song.pedals = form.pedals.data
        song.style = form.style.data
        song.groove = form.groove.data
        song.save()
        return redirect(url_for('site.profile'))
    return render_template('song_form.html', form=form, error=error)

@site.route('/song/<id>/remove', methods=["GET", "POST"])
@login_required
def songRemove(id):
    song = Song.get_by_id(id)
    song.delete()
    return redirect(url_for('site.profile'))

app/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Create Your Tone</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/main.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>


        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {height: 900px}

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #b89292;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: rgb(36, 42, 11);
            color: rgba(238, 240, 233, 20.758);
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
            height: auto;
            padding: 15px;
            }
            .row.content {height:auto;}
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('site.home') }}">MUSIC</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('site.home') }}">Home</a></li>
                    {% if current_user.is_authenticated %}
                    <li class="active"><a href="{{ url_for('auth.logout') }}">Hi {{ current_user.name }}! Logout</a></li>
                    <li class="active"><a href="{{ url_for('site.profile') }}">Keep Record of your tones</a></li>
                    {% else %}
                    <li class="active"><a href="{{ url_for('auth.signup') }}">Sign up</a></li>
                    <li class="active"><a href="{{ url_for('auth.login') }}">Sign in</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid text-center">
        {% block content %}{% endblock %}
    </div>

    <footer class="container-fluid text-center">
        <p>Rock Your Tone Brah</p>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>